/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package univs.edu.telas;

import univs.edu.funcionario.Funcionario;

/**
 *
 * @author LABORATORIO 01
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Funcionario funcionario;
    
    public MenuPrincipal(Funcionario funcionario) {
        initComponents();
        this.funcionario = funcionario;
        jlNome.setText("Bem Vindo: "+ funcionario.getNome());
        nivelAcesso();
    }
    
    public void nivelAcesso(){
        if(!funcionario.getCargo().equals("Administrador")){
            jmFuncionario.setVisible(false);
            jmUsuario.setVisible(false);
            jbPesquisaFuncionario.setVisible(false);
            
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbPesquisaConsulta = new javax.swing.JButton();
        jbMarcarConsulta = new javax.swing.JButton();
        jbPesquisaCliente = new javax.swing.JButton();
        jbPesquisaFuncionario = new javax.swing.JButton();
        jbPesquisaDentista = new javax.swing.JButton();
        jlNome = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastros = new javax.swing.JMenu();
        jmUsuario = new javax.swing.JMenuItem();
        jmFuncionario = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/menu principal.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jbPesquisaConsulta.setBackground(new java.awt.Color(31, 31, 31));
        jbPesquisaConsulta.setFont(new java.awt.Font("Beyond The Mountains", 0, 18)); // NOI18N
        jbPesquisaConsulta.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisaConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/botao consultas.png"))); // NOI18N
        jbPesquisaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaConsultaActionPerformed(evt);
            }
        });

        jbMarcarConsulta.setBackground(new java.awt.Color(31, 31, 31));
        jbMarcarConsulta.setFont(new java.awt.Font("Beyond The Mountains", 0, 18)); // NOI18N
        jbMarcarConsulta.setForeground(new java.awt.Color(255, 255, 255));
        jbMarcarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/botao marcar consulta.png"))); // NOI18N
        jbMarcarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMarcarConsultaActionPerformed(evt);
            }
        });

        jbPesquisaCliente.setBackground(new java.awt.Color(31, 31, 31));
        jbPesquisaCliente.setFont(new java.awt.Font("Beyond The Mountains", 0, 18)); // NOI18N
        jbPesquisaCliente.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/botao clientes.png"))); // NOI18N
        jbPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaClienteActionPerformed(evt);
            }
        });

        jbPesquisaFuncionario.setBackground(new java.awt.Color(31, 31, 31));
        jbPesquisaFuncionario.setFont(new java.awt.Font("Beyond The Mountains", 0, 18)); // NOI18N
        jbPesquisaFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/botao funcionarios.png"))); // NOI18N
        jbPesquisaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaFuncionarioActionPerformed(evt);
            }
        });

        jbPesquisaDentista.setBackground(new java.awt.Color(31, 31, 31));
        jbPesquisaDentista.setFont(new java.awt.Font("Beyond The Mountains", 0, 18)); // NOI18N
        jbPesquisaDentista.setForeground(new java.awt.Color(255, 255, 255));
        jbPesquisaDentista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/univs/edu/imagens/botao dentistas.png"))); // NOI18N
        jbPesquisaDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisaDentistaActionPerformed(evt);
            }
        });

        jlNome.setFont(new java.awt.Font("Beyond The Mountains", 0, 18)); // NOI18N
        jlNome.setForeground(new java.awt.Color(255, 255, 255));
        jlNome.setText("Usuario");

        jButton1.setText("TICKETS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deslogar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jbPesquisaConsulta))
                                .addGap(50, 50, 50)
                                .addComponent(jbMarcarConsulta)
                                .addGap(70, 70, 70)
                                .addComponent(jbPesquisaCliente)
                                .addGap(62, 62, 62)
                                .addComponent(jbPesquisaDentista)))))
                .addGap(93, 93, 93)
                .addComponent(jbPesquisaFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMarcarConsulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPesquisaConsulta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPesquisaCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPesquisaDentista, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbPesquisaFuncionario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(167, 167, 167)
                .addComponent(jButton2)
                .addGap(49, 49, 49))
        );

        jMenuBar1.setBackground(new java.awt.Color(31, 31, 31));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jmCadastros.setText("Cadastros");

        jmUsuario.setText("Usuário");
        jmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioActionPerformed(evt);
            }
        });
        jmCadastros.add(jmUsuario);

        jmFuncionario.setText("Funcionário");
        jmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFuncionarioActionPerformed(evt);
            }
        });
        jmCadastros.add(jmFuncionario);

        jMenuItem2.setText("Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmCadastros.add(jMenuItem2);

        jMenuItem4.setText("Dentista");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmCadastros.add(jMenuItem4);

        jMenuBar1.add(jmCadastros);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        TelaDentista tela = new TelaDentista(funcionario);

        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCliente tela = new TelaCliente();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFuncionarioActionPerformed
        TelaNivelDeAcesso tela = new TelaNivelDeAcesso();
        tela.setVisible(true);

    }//GEN-LAST:event_jmFuncionarioActionPerformed

    private void jmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioActionPerformed
        TelaUsuario tela = new TelaUsuario();
        tela.setVisible(true);
    }//GEN-LAST:event_jmUsuarioActionPerformed

    private void jbPesquisaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaConsultaActionPerformed
        TelaPesquisaConsulta tela = new TelaPesquisaConsulta();
        tela.setVisible(true);
        
    }//GEN-LAST:event_jbPesquisaConsultaActionPerformed

    private void jbMarcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMarcarConsultaActionPerformed
        TelaConsulta tela = new TelaConsulta();
        tela.setVisible(true);
        
    }//GEN-LAST:event_jbMarcarConsultaActionPerformed

    private void jbPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaClienteActionPerformed
        TelaPesquisaCliente tela = new TelaPesquisaCliente();
        tela.setVisible(true);
      
    }//GEN-LAST:event_jbPesquisaClienteActionPerformed

    private void jbPesquisaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaFuncionarioActionPerformed
        TelaPesquisaNivel tela = new TelaPesquisaNivel();
        nivelAcesso();
        tela.setVisible(true);

    }//GEN-LAST:event_jbPesquisaFuncionarioActionPerformed

    private void jbPesquisaDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisaDentistaActionPerformed
        TelaPesquisaDentista tela = new TelaPesquisaDentista(funcionario);
        tela.setVisible(true);

    }//GEN-LAST:event_jbPesquisaDentistaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaTiketRespostas telaresposta = new TelaTiketRespostas(funcionario);
        telaresposta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaLogin telaloguin = new TelaLogin();
        telaloguin.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JButton jbMarcarConsulta;
    private javax.swing.JButton jbPesquisaCliente;
    private javax.swing.JButton jbPesquisaConsulta;
    private javax.swing.JButton jbPesquisaDentista;
    private javax.swing.JButton jbPesquisaFuncionario;
    private javax.swing.JLabel jlNome;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenuItem jmFuncionario;
    private javax.swing.JMenuItem jmUsuario;
    // End of variables declaration//GEN-END:variables
}
